INSERT INTO `entry` (`wordlist-id`, `word`, `POS`, `definition`) VALUES
	(?, "one", "number", "number 1"),
	(?, "two", "number", "to turn something in opposite directions at the same time"),
	(?, "I", "pronoun", "the person who is speaking or writing"),
	(?, "you", "pronoun", "person someone is speaking or writing to"),
	(?, "we", "pronoun", "used to refer to the speaker and other people together"),
	(?, "person", "noun", "man, woman, or child"),
	(?, "name", "noun", "what something or someone is called"),
	(?, "eye", "noun", "part of the body that you see with"),
	(?, "ear", "noun", "the part of the head that you hear with"),
	(?, "nose", "noun", "part of the face used for breathing and smelling"),
	(?, "tongue", "noun", "part of the mouth that tastes food and is used for speaking"),
	(?, "tooth", "noun", "hard white thing in the mouth used for biting and eating"),
	(?, "hand", "noun", "body part at the end of a person%s arm"),
	(?, "knee", "noun", "the middle part of your leg that bends"),
	(?, "blood", "noun", "red liquid in the bodies of people and animals"),
	(?, "bone", "noun", "hard pieces of a body that form the frame of an animal"),
	(?, "breast", "noun", "one of the two parts on the front of a woman%s body that produce milk when she has a baby"),
	(?, "liver", "noun", "to be alive"),
	(?, "skin", "noun", "outer layer of an animal%s or human%s body"),
	(?, "drink", "verb", "to put water in your body through your mouth"),
	(?, "die", "verb", "to stop living"),
	(?, "see", "verb", "to use your eyes to look at something"),
	(?, "hear", "verb", "to be aware of sound; to perceive with the ear"),
	(?, "come", "verb", "to move toward someone; go with someone"),
	(?, "new", "verb", "not old, recently born, built, or made"),
	(?, "full", "verb", "containing or holding as much as possible"),
	(?, "louse", "noun", "making a lot of noise"),
	(?, "dog", "noun", "small 4-legged animal that barks kept as a pet"),
	(?, "fish", "noun", "animal that swims and lives in the sea"),
	(?, "horn (animal part)", "noun", "in a manner wishing something to happen"),
	(?, "tree", "noun", "tall green plants in a forest"),
	(?, "leaf", "noun", "quality of being able to guide or influence others"),
	(?, "sun", "noun", "the hot shining star the earth moves around"),
	(?, "star", "noun", "a bright planet of gas in the night sky"),
	(?, "water", "noun", "clear liquid that forms the seas, rivers, and rain"),
	(?, "fire", "noun", "heat and the flame produced when burning"),
	(?, "stone", "noun", "hard, solid piece of rock"),
	(?, "path", "noun", "track made with stones/by walking over the ground"),
	(?, "mountain", "noun", "very high piece of land, higher than a hill"),
	(?, "night (dark time)", "noun", "time when sun does not shine");