INSERT INTO `entry` (`wordlist-id`, `word`, `POS`, `definition`) VALUES
	(?, "all", "adjective", "completely; totally"),
	(?, "animal", "noun", "a living creature that is not a plant or person"),
	(?, "bad", "adjective", "not good; wrong"),
	(?, "because", "conjunction", "for a reason"),
	(?, "bird", "noun", "animal with feathers that uses wings to fly"),
	(?, "black", "adjective", "color of the sky on a dark night"),
	(?, "blood", "noun", "red liquid in the bodies of people and animals"),
	(?, "child", "noun", "a very young person, between about 2 and 15"),
	(?, "count", "verb", "to add things together to find the total number"),
	(?, "day", "noun", "a period of 24 hours"),
	(?, "die", "verb", "to stop living"),
	(?, "dirty", "adjective", "not clean"),
	(?, "dog", "noun", "small 4-legged animal that barks kept as a pet"),
	(?, "dry", "adjective", "without water; not wet"),
	(?, "dull", "adjective", "when something is required or expected"),
	(?, "dust", "noun", "fine dry powder that builds up on surfaces"),
	(?, "earth", "noun", "planet we live on"),
	(?, "egg", "noun", "hard-shelled thing from which a young bird is born"),
	(?, "grease", "noun", "color between black and white"),
	(?, "father", "noun", "a male parent"),
	(?, "feather", "noun", "unpleasant feelings caused by being aware of danger"),
	(?, "fire", "noun", "heat and the flame produced when burning"),
	(?, "fish", "noun", "animal that swims and lives in the sea"),
	(?, "flower", "noun", "plant with a pretty head (e.g., a rose)"),
	(?, "good", "adjective", "excellent; high quality"),
	(?, "grass", "noun", "plants with narrow green leaves, grown on lawns"),
	(?, "green", "adjective", "color of young leaves"),
	(?, "heavy", "adjective", "having a lot of weight"),
	(?, "how", "adverb", "in what way something happens or is done"),
	(?, "hunt", "verb", "to search for wild animals to kill for food or sport"),
	(?, "husband", "noun", "married man"),
	(?, "ice", "noun", "frozen water "),
	(?, "if", "adverb", "introducing a condition for something to happen"),
	(?, "kill", "verb", "to end the life of a person or other living thing"),
	(?, "laugh", "verb", "to make a happy sound when something is funny"),
	(?, "leaf", "noun", "quality of being able to guide or influence others"),
	(?, "lie", "verb", "to say something that you know is not true"),
	(?, "live", "verb", "to be alive"),
	(?, "long", "adjective", "large distance from one end to the other"),
	(?, "louse", "noun", "making a lot of noise"),
	(?, "man", "noun", "an adult male human being"),
	(?, "meat", "noun", "the muscles and soft parts of animals or birds that is eaten as food"),
	(?, "mother", "noun", "a female who has a child or children"),
	(?, "mountain", "noun", "very high piece of land, higher than a hill"),
	(?, "name", "noun", "what something or someone is called"),
	(?, "narrow", "adjective", "long but not wide; a small distance from one side to the other compared to length"),
	(?, "new", "adjective", "not old, recently born, built, or made"),
	(?, "night", "noun", "time when sun does not shine "),
	(?, "not", "adverb", "word indicating the negative of verbs, adjectives, etc."),
	(?, "old", "adjective", "having existed for a long time, not young or new"),
	(?, "other", "adjective", "something else; not the first one"),
	(?, "person", "noun", "man, woman, or child"),
	(?, "play", "verb", "to do or perform a game or sport"),
	(?, "rain", "verb", "drops of water that fall out of clouds in the sky"),
	(?, "red", "adjective", "being the color of blood"),
	(?, "correct", "adjective", "true or accurate"),
	(?, "river", "noun", "flowing water that runs from mountains to the sea"),
	(?, "rope", "noun", "part of a plant that grows underground"),
	(?, "salt", "noun", "natural white substance used to flavor or preserve food"),
	(?, "sea", "noun", "place with a large amount of salt water"),
	(?, "sharp", "adjective", "having a thin edge or point that is able to cut"),
	(?, "short", "adjective", "small distance from one end to the other"),
	(?, "sing", "verb", "to make musical sounds with your voice"),
	(?, "sit", "verb", "to be in a resting position on a chair"),
	(?, "smooth", "adjective", "something that feels pleasant and flat when you touch it; not rough"),
	(?, "snake", "noun", "something that feels pleasant and flat when you touch it; not rough"),
	(?, "snow", "noun", "soft white pieces of frozen water falling from the clouds"),
	(?, "stand", "noun", "to be upright; not be sitting or lying down"),
	(?, "star", "noun", "a bright planet of gas in the night sky"),
	(?, "stone", "noun", "hard, solid piece of rock"),
	(?, "sun", "noun", "the hot shining star the earth moves around"),
	(?, "tail", "noun", "back end of an animal's body that sticks out"),
	(?, "thin", "noun", "not thick; not wide in size"),
	(?, "tree", "noun", "tall green plants in a forest"),
	(?, "vomit", "verb", "someone who works willingly without pay"),
	(?, "warm", "verb", "slightly hot; not very hot"),
	(?, "water", "noun", "clear liquid that forms the seas, rivers, and rain"),
	(?, "wet", "adjective", "covered or soaked with a liquid; not dry"),
	(?, "what", "pronoun", "asking for information about someone or something"),
	(?, "when", "adverb", "word you use to ask about the time or day"),
	(?, "where", "adverb", "word you use to ask the location of something"),
	(?, "white", "adjective", "lightest color; the color of fresh snow and milk"),
	(?, "who", "pronoun", "what or which person or people, to ask about, talking about"),
	(?, "wide", "adjective", "having a great distance from one side to the other"),
	(?, "wife", "verb", "married woman"),
	(?, "wind", "verb", "natural movement of outside air as part of the weather"),
	(?, "with", "preposition", "used to express that people or things are together"),
	(?, "woman", "noun", "adult female human being"),
	(?, "wood", "noun", "hard material that trees are made of and is used for building and fuel"),
	(?, "worm", "noun", "all the humans, events, activities on the earth"),
	(?, "year", "noun", "unit of time equal to 12 months"),
	(?, "yellow", "noun", "color of lemons or the sun"),
	(?, "full", "adjective", "containing or holding as much as possible"),
	(?, "moon", "noun", "round object circling the earth at night"),
	(?, "brother", "noun", "a boy or man who shares a parent with you"),
	(?, "cat", "noun", "a small animal of the lion and tiger family with four legs and a tail that is kept as a pet"),
	(?, "dance", "verb", "to move your body rhythmically to music"),
	(?, "pig", "noun", "farm animal that gives bacon and ham"),
	(?, "sister", "noun", "female you share a parent with"),
	(?, "work", "noun", "activity you do in order to make money");