INSERT INTO `entry` (`wordlist-id`, `word`, `POS`, `definition`) VALUES
	(?, "I", "pronoun", "the person who is speaking or writing"),
	(?, "you", "pronoun", "person someone is speaking or writing to"),
	(?, "we", "pronoun", "used to refer to the speaker and other people together"),
	(?, "this", "pronoun", "person, thing, or idea near you"),
	(?, "that", "pronoun", "used to show which person or thing we are talking about"),
	(?, "who", "pronoun", "what or which person or people, to ask about, talking about"),
	(?, "what", "pronoun", "asking for information about someone or something"),
	(?, "not", "adverb", "word indicating the negative of verbs, adjectives, etc."),
	(?, "all (of a number)", "quantifier", "completely; totally"),
	(?, "many", "quantifier", "used to refer to a large number of things"),
	(?, "one", "number", "number 1"),
	(?, "two", "number", "to turn something in opposite directions at the same time"),
	(?, "big", "adjective", "large"),
	(?, "long (not wide)", "adjective", "large distance from one end to the other"),
	(?, "small", "adjective", "little in size; not big"),
	(?, "woman", "noun", "adult female human being"),
	(?, "man (adult male human)", "noun", "an adult male human being"),
	(?, "person (individual human)", "noun", "man, woman, or child"),
	(?, "fish", "noun", "animal that swims and lives in the sea"),
	(?, "bird", "noun", "animal with feathers that uses wings to fly"),
	(?, "dog", "noun", "small 4-legged animal that barks kept as a pet"),
	(?, "louse", "noun", "making a lot of noise"),
	(?, "tree (not log)", "noun", "tall green plants in a forest"),
	(?, "seed", "noun", "a small object made by a plant from which a new plant can grow; the beginning of something"),
	(?, "leaf", "noun", "quality of being able to guide or influence others"),
	(?, "root", "noun", "part of a plant that grows underground"),
	(?, "bark (of tree)", "noun", "almost not possible or does not happen"),
	(?, "skin", "noun", "outer layer of an animal%s or human%s body"),
	(?, "meat, flesh", "noun", "the muscles and soft parts of animals or birds that is eaten as food"),
	(?, "blood", "noun", "red liquid in the bodies of people and animals"),
	(?, "bone", "noun", "hard pieces of a body that form the frame of an animal"),
	(?, "grease, fat", "noun", "color between black and white"),
	(?, "egg", "noun", "hard-shelled thing from which a young bird is born"),
	(?, "horn (of bull etc.)", "noun", "in a manner wishing something to happen"),
	(?, "tail", "noun", "back end of an animal%s body that sticks out"),
	(?, "feather", "noun", "unpleasant feelings caused by being aware of danger"),
	(?, "hair", "noun", "long thin strands on your head or body"),
	(?, "head", "noun", "top part of your body with eyes and a mouth"),
	(?, "ear", "noun", "the part of the head that you hear with"),
	(?, "eye", "noun", "part of the body that you see with"),
	(?, "nose", "noun", "part of the face used for breathing and smelling"),
	(?, "mouth", "noun", "part of the face used for eating and talking"),
	(?, "tooth", "noun", "hard white thing in the mouth used for biting and eating"),
	(?, "tongue", "noun", "part of the mouth that tastes food and is used for speaking"),
	(?, "claw", "noun", "a separate part of a contract, a will, or another legal document"),
	(?, "foot (not leg)", "noun", "lowest part of the leg we use to stand on"),
	(?, "knee", "noun", "the middle part of your leg that bends"),
	(?, "hand", "noun", "body part at the end of a person%s arm"),
	(?, "belly (abdomen)", "noun", "a hollow metal object shaped like a cup that rings when it is hit"),
	(?, "neck (not nape)", "noun", "part of the body joining the head and the body"),
	(?, "breasts", "noun", "one of the two parts on the front of a woman%s body that produce milk when she has a baby"),
	(?, "heart", "noun", "part of the body that pumps blood"),
	(?, "liver", "noun", "to be alive"),
	(?, "drink", "verb", "to put water in your body through your mouth"),
	(?, "eat", "verb", "to put food in your mouth"),
	(?, "bite", "verb", "to press down on or cut into something with the teeth"),
	(?, "see ", "verb", "to use your eyes to look at something"),
	(?, "hear", "verb", "to be aware of sound; to perceive with the ear"),
	(?, "know (facts)", "verb", "to have knowledge of things in your mind"),
	(?, "sleep", "verb", "to rest your body in bed, as at night time"),
	(?, "die", "verb", "to stop living"),
	(?, "kill", "verb", "to end the life of a person or other living thing"),
	(?, "swim", "verb", "to move through water by moving parts of the body"),
	(?, "fly", "verb", "to travel through the air using wings"),
	(?, "walk", "verb", "to move with your legs at a slowish pace"),
	(?, "come", "verb", "to move toward someone; go with someone"),
	(?, "lie (on side, recline)", "verb", "to say something that you know is not true"),
	(?, "sit", "verb", "to be in a resting position on a chair"),
	(?, "stand", "verb", "to be upright; not be sitting or lying down"),
	(?, "give", "verb", "to hand over or present something to someone"),
	(?, "say", "verb", "to use words to tell a message"),
	(?, "sun", "noun", "the hot shining star the earth moves around"),
	(?, "moon", "noun", "round object circling the earth at night"),
	(?, "star", "noun", "a bright planet of gas in the night sky"),
	(?, "water", "noun", "clear liquid that forms the seas, rivers, and rain"),
	(?, "rain", "noun", "drops of water that fall out of clouds in the sky"),
	(?, "stone", "noun", "hard, solid piece of rock"),
	(?, "sand", "noun", "grains of rock that make beaches and deserts"),
	(?, "earth (soil)", "verb", "planet we live on"),
	(?, "cloud (not fog)", "noun", "a mass of water vapor in the sky, as when it is going to rain"),
	(?, "smoke (of fire)", "noun", "to breathe in through a cigarette and then blow it out"),
	(?, "fire", "noun", "heat and the flame produced when burning"),
	(?, "ash(es)", "noun", "a word used to compare two equal things"),
	(?, "burn", "noun", "to destroy with fire"),
	(?, "path (road, trail; not street)", "noun", "track made with stones/by walking over the ground"),
	(?, "mountain (not hill)", "noun", "very high piece of land, higher than a hill"),
	(?, "red", "adjective", "being the color of blood"),
	(?, "green", "adjective", "color of young leaves"),
	(?, "yellow", "adjective", "color of lemons or the sun"),
	(?, "white", "adjective", "lightest color; the color of fresh snow and milk"),
	(?, "black", "adjective", "color of the sky on a dark night"),
	(?, "night", "adjective", "time when sun does not shine "),
	(?, "hot (of weather)", "adjective", "having a high temperature"),
	(?, "cold (of weather)", "adjective", "having a very low temperature"),
	(?, "full", "adjective", "containing or holding as much as possible"),
	(?, "new", "adjective", "not old, recently born, built, or made"),
	(?, "good", "adjective", "excellent; high quality"),
	(?, "round", "adjective", "being in the shape of a circle or ball"),
	(?, "dry", "adjective", "without water; not wet"),
	(?, "name", "noun", "what something or someone is called");