INSERT INTO `entry` (`wordlist-id`, `word`, `POS`, `definition`) VALUES
	(?, "I", "pronoun", "the person who is speaking or writing"),
	(?, "you (sg), thou", "pronoun", "person someone is speaking or writing to"),
	(?, "he", "pronoun", "object form of a male person you are talking about"),
	(?, "we", "pronoun", "used to refer to the speaker and other people together"),
	(?, "you (pl)", "pronoun", "person someone is speaking or writing to"),
	(?, "they", "pronoun", "used to refer to two or more people, animals, or things"),
	(?, "this", "pronoun", "person, thing, or idea near you"),
	(?, "that", "pronoun", "used to show which person or thing we are talking about"),
	(?, "here", "pronoun", "in, at, or to this position or place"),
	(?, "there", "pronoun", "in that place or position, at that location"),
	(?, "who", "pronoun", "what or which person or people, to ask about, talking about"),
	(?, "what", "pronoun", "asking for information about someone or something"),
	(?, "where", "adverb", "word you use to ask the location of something"),
	(?, "when", "adverb", "word you use to ask about the time or day"),
	(?, "how", "adverb", "in what way something happens or is done"),
	(?, "not", "adverb", "word indicating the negative of verbs, adjectives, etc."),
	(?, "all", "quantifier", "completely; totally"),
	(?, "many", "quantifier", "used to refer to a large number of things"),
	(?, "some", "quantifier", "used to refer to a person or thing that is not known"),
	(?, "few", "quantifier", "not many; small in number"),
	(?, "other", "quantifier", "something else; not the first one"),
	(?, "one", "number", "number 1"),
	(?, "two", "number", "to turn something in opposite directions at the same time"),
	(?, "three", "number", "to say you will harm or hurt someone"),
	(?, "four", "number", "underground base on which a building is constructed"),
	(?, "five", "number", "proper or acceptable; morally or socially correct"),
	(?, "big", "adjective", "large"),
	(?, "long", "adjective", "large distance from one end to the other"),
	(?, "wide", "adjective", "having a great distance from one side to the other"),
	(?, "thick", "adjective", "having a large distance between two surfaces"),
	(?, "heavy", "adjective", "having a lot of weight"),
	(?, "small", "adjective", "little in size; not big"),
	(?, "short", "adjective", "small distance from one end to the other"),
	(?, "narrow", "adjective", "long but not wide; a small distance from one side to the other compared to length"),
	(?, "thin", "adjective", "not thick; not wide in size"),
	(?, "woman", "noun", "adult female human being"),
	(?, "man (adult male)", "noun", "an adult male human being"),
	(?, "man (human being)", "noun", "an adult male human being"),
	(?, "child (a youth)", "noun", "a very young person, between about 2 and 15"),
	(?, "wife", "noun", "married woman"),
	(?, "husband", "noun", "married man"),
	(?, "mother", "noun", "a female who has a child or children"),
	(?, "father", "noun", "a male parent"),
	(?, "animal", "noun", "a living creature that is not a plant or person"),
	(?, "fish", "noun", "animal that swims and lives in the sea"),
	(?, "bird", "noun", "animal with feathers that uses wings to fly"),
	(?, "dog", "noun", "small 4-legged animal that barks kept as a pet"),
	(?, "louse", "noun", "making a lot of noise"),
	(?, "snake", "noun", "something that feels pleasant and flat when you touch it; not rough"),
	(?, "worm", "noun", "all the humans, events, activities on the earth"),
	(?, "tree", "noun", "tall green plants in a forest"),
	(?, "forest", "noun", "large area with many trees"),
	(?, "stick (of wood)", "noun", "long thin piece of wood from a tree"),
	(?, "fruit", "noun", "food that grows on a tree or bush"),
	(?, "seed", "noun", "a small object made by a plant from which a new plant can grow; the beginning of something"),
	(?, "leaf", "noun", "quality of being able to guide or influence others"),
	(?, "root", "noun", "part of a plant that grows underground"),
	(?, "bark (of tree)", "noun", "almost not possible or does not happen"),
	(?, "flower", "noun", "plant with a pretty head (e.g., a rose)"),
	(?, "grass", "noun", "plants with narrow green leaves, grown on lawns"),
	(?, "rope", "noun", "part of a plant that grows underground"),
	(?, "skin (of a person)", "noun", "outer layer of an animal's or human's body"),
	(?, "meat (as in flesh)", "noun", "the muscles and soft parts of animals or birds that is eaten as food"),
	(?, "blood", "noun", "red liquid in the bodies of people and animals"),
	(?, "bone", "noun", "hard pieces of a body that form the frame of an animal"),
	(?, "fat (noun)", "noun", "oily part of meat"),
	(?, "egg", "noun", "hard-shelled thing from which a young bird is born"),
	(?, "horn", "noun", "in a manner wishing something to happen"),
	(?, "tail", "noun", "back end of an animal's body that sticks out"),
	(?, "feather (rather not down)", "noun", "unpleasant feelings caused by being aware of danger"),
	(?, "hair", "noun", "long thin strands on your head or body"),
	(?, "head", "noun", "top part of your body with eyes and a mouth"),
	(?, "ear", "noun", "the part of the head that you hear with"),
	(?, "eye", "noun", "part of the body that you see with"),
	(?, "nose", "noun", "part of the face used for breathing and smelling"),
	(?, "mouth", "noun", "part of the face used for eating and talking"),
	(?, "tooth (rather not molar)", "noun", "hard white thing in the mouth used for biting and eating"),
	(?, "tongue", "noun", "part of the mouth that tastes food and is used for speaking"),
	(?, "fingernail", "noun", "one of the five long parts of the hand"),
	(?, "foot", "noun", "lowest part of the leg we use to stand on"),
	(?, "leg", "noun", "part of the body from the thigh down"),
	(?, "knee", "noun", "the middle part of your leg that bends"),
	(?, "hand", "noun", "body part at the end of a person's arm"),
	(?, "wing", "noun", "part of an animal's body that is used for flying"),
	(?, "belly", "noun", "a hollow metal object shaped like a cup that rings when it is hit"),
	(?, "guts", "noun", "a weapon that shoots small metal objects down a metal tube"),
	(?, "neck", "noun", "part of the body joining the head and the body"),
	(?, "back", "noun", "behind; to the rear; previous "),
	(?, "breast", "noun", "one of the two parts on the front of a woman's body that produce milk when she has a baby"),
	(?, "heart", "noun", "part of the body that pumps blood"),
	(?, "liver", "noun", "to be alive"),
	(?, "drink", "verb", "to put water in your body through your mouth"),
	(?, "eat", "verb", "to put food in your mouth"),
	(?, "bite", "verb", "to press down on or cut into something with the teeth"),
	(?, "suck", "verb", "so like, or similar"),
	(?, "spit", "verb", "part of a person that is not physical and believed to be the source of human emotions and character"),
	(?, "vomit", "verb", "someone who works willingly without pay"),
	(?, "blow (as wind)", "verb", "to move something using air"),
	(?, "breathe", "verb", "to move air into and out of your lungs"),
	(?, "laugh", "verb", "to make a happy sound when something is funny"),
	(?, "see", "verb", "to use your eyes to look at something"),
	(?, "hear", "verb", "to be aware of sound; to perceive with the ear"),
	(?, "know (a fact)", "verb", "to have knowledge of things in your mind"),
	(?, "think", "verb", "to have an idea, opinion, or belief about something"),
	(?, "smell (sense odor)", "verb", "to use your nose to sense something"),
	(?, "fear", "verb", "unpleasant feelings caused by being aware of danger"),
	(?, "sleep", "verb", "to rest your body in bed, as at night time"),
	(?, "live", "verb", "to be alive"),
	(?, "die", "verb", "to stop living"),
	(?, "kill", "verb", "to end the life of a person or other living thing"),
	(?, "fight", "verb", "act of trying to hurt someone by hitting them"),
	(?, "hunt (transitive)", "verb", "to search for wild animals to kill for food or sport"),
	(?, "hit", "verb", "to fight, attack or damage something or someone"),
	(?, "cut", "verb", "to use a knife or scissors to divide or open the surface"),
	(?, "split", "verb", "to break something into pieces or divide something"),
	(?, "stab (or stick)", "verb", "shape with four sides of equal length sides and four right (90°) angles"),
	(?, "scratch (an itch)", "verb", "to get points in a sport such as kicking a ball into a goal"),
	(?, "dig", "verb", "to move material to create a hole"),
	(?, "swim", "verb", "to move through water by moving parts of the body"),
	(?, "fly", "verb", "to travel through the air using wings"),
	(?, "walk", "verb", "to move with your legs at a slowish pace"),
	(?, "come", "verb", "to move toward someone; go with someone"),
	(?, "lie (as on one's side)", "verb", "to say something that you know is not true"),
	(?, "sit", "verb", "to be in a resting position on a chair"),
	(?, "stand", "verb", "to be upright; not be sitting or lying down"),
	(?, "turn (change direction)", "verb", "to change the direction of something (e.g., a car)"),
	(?, "fall (as in drop)", "verb", "dropping from a standing position to the ground"),
	(?, "give", "verb", "to hand over or present something to someone"),
	(?, "hold", "verb", "to use hands or arms to carry or keep something"),
	(?, "squeeze", "verb", "shape with four sides of equal length sides and four right (90°) angles"),
	(?, "rub", "verb", "concerning a king or queen"),
	(?, "wash", "verb", "to clean someone or something with soap and water"),
	(?, "wipe", "verb", "to clean or dry something with a cloth"),
	(?, "pull", "verb", "to hold something and move it toward you"),
	(?, "push", "verb", "to force something away from you"),
	(?, "throw", "verb", "to use your arm to make a thing fly through the air"),
	(?, "tie", "verb", "to join together two ends of string or rope; to join two or more things together with string or rope"),
	(?, "sew", "verb", "very bad; very serious"),
	(?, "count", "verb", "to add things together to find the total number"),
	(?, "say", "verb", "to use words to tell a message"),
	(?, "sing", "verb", "to make musical sounds with your voice"),
	(?, "play", "verb", "to do or perform a game or sport"),
	(?, "float", "verb", "to stay on the surface of a liquid and not sink"),
	(?, "flow", "verb", "to move steadily and easily in a certain direction"),
	(?, "freeze", "verb", "to become hard because of very cold temperatures"),
	(?, "swell", "verb", "tasting like sugar; containing sugar"),
	(?, "sun", "noun", "the hot shining star the earth moves around"),
	(?, "moon", "noun", "round object circling the earth at night"),
	(?, "star", "noun", "a bright planet of gas in the night sky"),
	(?, "water", "noun", "clear liquid that forms the seas, rivers, and rain"),
	(?, "rain", "noun", "drops of water that fall out of clouds in the sky"),
	(?, "river", "noun", "flowing water that runs from mountains to the sea"),
	(?, "lake", "noun", "a large area of water surrounded by land"),
	(?, "sea (as in ocean)", "noun", "place with a large amount of salt water"),
	(?, "salt", "noun", "natural white substance used to flavor or preserve food"),
	(?, "stone", "noun", "hard, solid piece of rock"),
	(?, "sand", "noun", "grains of rock that make beaches and deserts"),
	(?, "dust", "noun", "fine dry powder that builds up on surfaces"),
	(?, "earth (as in soil)", "noun", "planet we live on"),
	(?, "cloud", "noun", "a mass of water vapor in the sky, as when it is going to rain"),
	(?, "fog", "noun", "main purpose or center of interest or activity"),
	(?, "sky", "noun", "the place where we see clouds above us"),
	(?, "wind (as in breeze)", "noun", "natural movement of outside air as part of the weather"),
	(?, "snow", "noun", "soft white pieces of frozen water falling from the clouds"),
	(?, "ice", "noun", "frozen water "),
	(?, "smoke", "noun", "to breathe in through a cigarette and then blow it out"),
	(?, "fire", "noun", "heat and the flame produced when burning"),
	(?, "ashes", "noun", "feeling shame or guilt because you did something wrong"),
	(?, "to burn (intransitive)", "verb", "move towards; in the direction of"),
	(?, "road", "noun", "long piece of hard land for cars to travel on"),
	(?, "mountain", "noun", "very high piece of land, higher than a hill"),
	(?, "red", "adjective", "being the color of blood"),
	(?, "green", "adjective", "color of young leaves"),
	(?, "yellow", "adjective", "color of lemons or the sun"),
	(?, "white", "adjective", "lightest color; the color of fresh snow and milk"),
	(?, "black", "adjective", "color of the sky on a dark night"),
	(?, "night", "noun", "time when sun does not shine "),
	(?, "day (daytime)", "noun", "a period of 24 hours"),
	(?, "year", "noun", "unit of time equal to 12 months"),
	(?, "warm (as in weather)", "adjective", "slightly hot; not very hot"),
	(?, "cold (as in weather)", "adjective", "having a very low temperature"),
	(?, "full", "adjective", "containing or holding as much as possible"),
	(?, "new", "adjective", "not old, recently born, built, or made"),
	(?, "old", "adjective", "having existed for a long time, not young or new"),
	(?, "good", "adjective", "excellent; high quality"),
	(?, "bad", "adjective", "not good; wrong"),
	(?, "rotten (as, a log)", "adjective", "a red flower used to show love"),
	(?, "dirty", "adjective", "not clean"),
	(?, "straight", "adjective", "not having curves, bends, or angles"),
	(?, "round", "adjective", "being in the shape of a circle or ball"),
	(?, "sharp (as a knife)", "adjective", "having a thin edge or point that is able to cut"),
	(?, "dull (as a knife)", "adjective", "when something is required or expected"),
	(?, "smooth", "adjective", "something that feels pleasant and flat when you touch it; not rough"),
	(?, "wet", "adjective", "covered or soaked with a liquid; not dry"),
	(?, "dry", "adjective", "without water; not wet"),
	(?, "right (correct)", "adjective", "on side where the hand that most people write with"),
	(?, "near", "adjective", "with a small distance between things"),
	(?, "far", "adjective", "a long way away"),
	(?, "right (side)", "adjective", "on side where the hand that most people write with"),
	(?, "left (side)", "adjective", "side of your body your heart is on"),
	(?, "at", "preposition", "in the place where something is"),
	(?, "in", "preposition", "being inside something"),
	(?, "with (accompanying)", "conjunction", "used to express that people or things are together"),
	(?, "and", "conjunction", "used to refer to two or more things"),
	(?, "if", "conjunction", "introducing a condition for something to happen"),
	(?, "because", "conjunction", "for a reason"),
	(?, "name", "noun", "what something or someone is called");