INSERT INTO `entry` (`wordlist-id`, `word`, `POS`, `definition`) VALUES
	(?, "I", "pronoun", "the person who is speaking or writing"),
	(?, "you (singular)", "pronoun", "person someone is speaking or writing to"),
	(?, "this", "pronoun", "person, thing, or idea near you"),
	(?, "who", "pronoun", "what or which person or people, to ask about, talking about"),
	(?, "what", "pronoun", "asking for information about someone or something"),
	(?, "one", "number", "number 1"),
	(?, "two", "number", "to turn something in opposite directions at the same time"),
	(?, "fish", "noun", "animal that swims and lives in the sea"),
	(?, "dog", "noun", "small 4-legged animal that barks kept as a pet"),
	(?, "louse", "noun", "making a lot of noise"),
	(?, "blood", "noun", "red liquid in the bodies of people and animals"),
	(?, "bone", "noun", "hard pieces of a body that form the frame of an animal"),
	(?, "egg", "noun", "hard-shelled thing from which a young bird is born"),
	(?, "horn", "noun", "in a manner wishing something to happen"),
	(?, "tail", "noun", "back end of an animal%s body that sticks out"),
	(?, "ear", "noun", "the part of the head that you hear with"),
	(?, "eye", "noun", "part of the body that you see with"),
	(?, "nose", "noun", "part of the face used for breathing and smelling"),
	(?, "tooth", "noun", "hard white thing in the mouth used for biting and eating"),
	(?, "tongue", "noun", "part of the mouth that tastes food and is used for speaking"),
	(?, "hand", "noun", "body part at the end of a person%s arm"),
	(?, "know", "verb", "to have knowledge of things in your mind"),
	(?, "die", "verb", "to stop living"),
	(?, "give", "verb", "to hand over or present something to someone"),
	(?, "sun", "noun", "the hot shining star the earth moves around"),
	(?, "moon", "noun", "round object circling the earth at night"),
	(?, "water", "noun", "clear liquid that forms the seas, rivers, and rain"),
	(?, "salt", "noun", "natural white substance used to flavor or preserve food"),
	(?, "stone", "noun", "hard, solid piece of rock"),
	(?, "wind", "noun", "natural movement of outside air as part of the weather"),
	(?, "fire", "noun", "heat and the flame produced when burning"),
	(?, "year", "noun", "unit of time equal to 12 months"),
	(?, "full", "adjective", "containing or holding as much as possible"),
	(?, "new", "adjective", "not old, recently born, built, or made"),
	(?, "name", "noun", "what something or someone is called");